import test from 'node:test'
import assert from 'node:assert/strict'
import { createTestDatabase, read, command, quizAnswers, ids, uuid } from './harness.mjs'

test('account settings, streak, daily review and analytics follow server policies',async t=>{
 const db=await createTestDatabase()
 t.after(()=>db.close())
 const fail=(promise,code='22023')=>assert.rejects(promise,error=>error.code===code)
 await t.test('settings validate safe flags and audited timezone cooldown',async()=>{
  const settings=await read(db,'settings')
  assert.equal(settings.timezone,'Asia/Ho_Chi_Minh')
  assert.equal(settings.analyticsEnabled,false)
  await fail(command(db,'update_settings',{timezone:'invalid-zone',operationId:'timezone-invalid'}))
  await fail(command(db,'update_settings',{role:'admin',operationId:'role-spoof'}))
  await fail(command(db,'update_settings',{soundMuted:'yes',operationId:'sound-invalid'}))
  const changed=await command(db,'update_settings',{timezone:'America/Adak',soundMuted:true,reducedMotion:true,operationId:'timezone-change'})
  assert.equal(changed.soundMuted,true)
  assert.equal(changed.reducedMotion,true)
  assert.equal(changed.timezone,'America/Adak')
  await fail(command(db,'update_settings',{timezone:'Pacific/Kiritimati',operationId:'timezone-repeat'}),'40001')
  assert.equal((await db.query("select count(*) count from private.audit_events where user_id=$1 and kind='timezone_changed'",[ids.userA])).rows[0].count,1)
 })
 await t.test('enabled daily review earns5 once per account day; attempt cannot replay into another timezone day',async()=>{
  const unflagged=await command(db,'submit_practice',{questionSetId:ids.unflaggedPractice,answers:quizAnswers(),operationId:'unflagged-attempt'})
  await fail(command(db,'complete_daily_review',{questionSetId:ids.unflaggedPractice,attemptId:unflagged.attemptId,operationId:'unflagged-review'}))
  const first=await command(db,'submit_practice',{questionSetId:ids.practice,answers:quizAnswers(),operationId:'daily-attempt'})
  const review=await command(db,'complete_daily_review',{questionSetId:ids.practice,attemptId:first.attemptId,operationId:'daily-review'})
  assert.equal(review.xpGranted,5)
  assert.equal(review.currentStreak,1)
  const retry=await command(db,'complete_daily_review',{questionSetId:ids.practice,attemptId:first.attemptId,operationId:'daily-again'})
  assert.equal(retry.xpGranted,0)
  assert.equal(retry.alreadyCompleted,true)
  const another=await command(db,'submit_practice',{questionSetId:ids.practice,answers:quizAnswers(false),operationId:'daily-second-attempt'})
  assert.equal((await command(db,'complete_daily_review',{questionSetId:ids.practice,attemptId:another.attemptId,operationId:'daily-second-review'})).xpGranted,0)
  // Trusted audit clock fixture permits a first timezone shift without a wall-clock seven-day wait.
  await db.query("update public.user_settings set timezone_changed_at=now()-interval '8 days' where user_id=$1",[ids.userA])
  await command(db,'update_settings',{timezone:'Pacific/Kiritimati',operationId:'timezone-forward'})
  const replay=await command(db,'complete_daily_review',{questionSetId:ids.practice,attemptId:first.attemptId,operationId:'daily-tz-replay'})
  assert.equal(replay.xpGranted,0)
  assert.equal(replay.localDate,review.localDate)
  const shifted=await command(db,'submit_practice',{questionSetId:ids.practice,answers:quizAnswers(),operationId:'shifted-attempt'})
  await fail(command(db,'complete_daily_review',{questionSetId:ids.practice,attemptId:shifted.attemptId,operationId:'shifted-review'}),'40001')
  assert.equal((await read(db,'account')).totalXp,5)
  await fail(command(db,'complete_daily_review',{questionSetId:ids.practice,attemptId:first.attemptId,operationId:'b-claims-a'},ids.userB))
 })
 await t.test('yesterday extends streak, old gap resets current, longest survives',async()=>{
  const today=(await db.query("select (now() at time zone 'Asia/Ho_Chi_Minh')::date::text as local_day")).rows[0].local_day
  await db.query("update public.user_streaks set current_streak=4,longest_streak=7,last_qualified_local_date=$2::date-1 where user_id=$1",[ids.userB,today])
  await command(db,'complete_block',{lessonId:ids.lesson,blockId:ids.textBlock,operationId:'b-text'},ids.userB)
  await command(db,'complete_lesson',{lessonId:ids.lesson,operationId:'b-lesson'},ids.userB)
  const b=await read(db,'account',null,null,ids.userB)
  assert.equal(b.currentStreak,5)
  assert.equal(b.longestStreak,7)
  await db.query("update public.user_streaks set last_qualified_local_date=$2::date-3 where user_id=$1",[ids.userB,today])
  assert.equal((await read(db,'account',null,null,ids.userB)).currentStreak,0)
  // Remove only synthetic mutable day fixture; append-only ledger remains unchanged.
  await db.query('delete from public.streak_days where user_id=$1',[ids.userB])
  await command(db,'submit_scored',{questionSetId:ids.quiz,answers:quizAnswers(),operationId:'b-new-activity'},ids.userB)
  const reset=await read(db,'account',null,null,ids.userB)
  assert.equal(reset.currentStreak,1)
  assert.equal(reset.longestStreak,7)
 })
 await t.test('analytics is optional, event-specific and rejects personal data fields',async()=>{
  await command(db,'track',{name:'lesson_started',properties:{lesson_id:ids.lesson,version:'1'},operationId:'analytics-optout'})
  assert.equal((await db.query('select count(*) count from public.analytics_events')).rows[0].count,0)
  await command(db,'update_settings',{analyticsEnabled:true,operationId:'analytics-optin'})
  await command(db,'track',{name:'lesson_started',properties:{lesson_id:ids.lesson,version:'1'},operationId:'analytics-valid'})
  assert.equal((await db.query('select count(*) count from public.analytics_events')).rows[0].count,1)
  await fail(command(db,'track',{name:'lesson_started',properties:{email:'fixture@example.test'},operationId:'analytics-email'}))
  await fail(command(db,'track',{name:'lesson_started',properties:{lesson_id:'fixture@example.test'},operationId:'analytics-disguised'}))
  await fail(command(db,'track',{name:'lesson_started',properties:{scene_id:uuid(9)},operationId:'analytics-other-event'}))
  // Analytics rejection does not roll back the independently committed trusted lesson operation.
  await command(db,'complete_block',{lessonId:ids.lesson,blockId:ids.textBlock,operationId:'analytics-learning-text'})
  await command(db,'complete_lesson',{lessonId:ids.lesson,operationId:'analytics-learning-complete'})
  assert.equal((await read(db,'lesson_progress',ids.lesson)).status,'completed')
 })
 await t.test('expectedSubject is a session guard and never overrides authenticated identity',async()=>{
  await fail(command(db,'complete_block',{lessonId:ids.mixedLesson,blockId:ids.recapBlock,expectedSubject:ids.userA,operationId:'session-changed'},ids.userB),'42501')
  assert.equal((await read(db,'lesson_progress',ids.mixedLesson,null,ids.userB)),null)
  assert.equal((await db.query('select count(*) count from private.operations where user_id=$1 and operation_id=$2',[ids.userB,'session-changed'])).rows[0].count,0)
  const beforeA=await read(db,'settings'),beforeB=await read(db,'settings',null,null,ids.userB)
  await fail(command(db,'update_settings',{soundMuted:!beforeA.soundMuted,expectedSubject:ids.userA,operationId:'changed-settings-session'},ids.userB),'42501')
  assert.deepEqual(await read(db,'settings'),beforeA)
  assert.deepEqual(await read(db,'settings',null,null,ids.userB),beforeB)
  const changed=await command(db,'update_settings',{soundMuted:!beforeA.soundMuted,expectedSubject:ids.userA,operationId:'owned-settings-session'})
  assert.equal(changed.soundMuted,!beforeA.soundMuted)
  assert.deepEqual(await read(db,'settings',null,null,ids.userB),beforeB)
 })
})
