import test from 'node:test'
import assert from 'node:assert/strict'
import { createTestDatabase, read, command, quizAnswers, ids } from './harness.mjs'

test('trusted SQL completion, grading, resume and retries preserve account rewards', async t => {
  const db=await createTestDatabase()
  t.after(()=>db.close())
  const fail=(promise,code='22023')=>assert.rejects(promise,error=>error.code===code)
  const cmd=(kind,input,user)=>command(db,kind,input,user)
  const block=(lessonId,blockId,operationId,method)=>cmd('complete_block',{lessonId,blockId,operationId,...(method?{method}:{})})
  await t.test('checkpoints cannot spoof completed blocks and revision conflicts cannot rewind',async()=>{
    await fail(cmd('save_lesson_checkpoint',{lessonId:ids.lesson,currentBlockId:ids.textBlock,completedBlockIds:[ids.textBlock],operationId:'spoof'}))
    const first=await cmd('save_lesson_checkpoint',{lessonId:ids.lesson,currentBlockId:ids.textBlock,completedBlockIds:[],expectedRevision:0,operationId:'checkpoint'})
    assert.equal(first.revision,1)
    assert.deepEqual(first.confirmedCompletedBlockIds,[])
    await fail(cmd('save_lesson_checkpoint',{lessonId:ids.lesson,currentBlockId:ids.textBlock,completedBlockIds:[],expectedRevision:0,operationId:'stale'}),'PT409')
    assert.deepEqual(await cmd('save_lesson_checkpoint',{lessonId:ids.lesson,currentBlockId:ids.textBlock,completedBlockIds:[],expectedRevision:0,operationId:'checkpoint'}),first)
    await fail(cmd('save_lesson_checkpoint',{lessonId:ids.mixedLesson,currentBlockId:ids.textBlock,completedBlockIds:[],operationId:'wrong-parent'}),'P0002')
    await fail(cmd('complete_lesson',{lessonId:ids.lesson,operationId:'premature'}))
  })
  await t.test('explicit text completion and concurrent distinct completion operations grant exactly10',async()=>{
    const text=await block(ids.lesson,ids.textBlock,'text')
    assert.equal(text.xpGranted,0)
    const [a,b]=await Promise.all([cmd('complete_lesson',{lessonId:ids.lesson,operationId:'lesson-a'}),cmd('complete_lesson',{lessonId:ids.lesson,operationId:'lesson-b'})])
    assert.equal(a.xpGranted+b.xpGranted,10)
    assert.equal((await read(db,'account')).currentStreak,1)
    const replay=await cmd('complete_lesson',{lessonId:ids.lesson,operationId:'lesson-a'})
    assert.deepEqual(replay,a)
    assert.equal((await read(db,'account')).totalXp,10)
    await fail(cmd('complete_lesson',{lessonId:ids.videoLesson,operationId:'lesson-a'}),'PT409')
    const saved=await cmd('save_lesson_checkpoint',{lessonId:ids.lesson,completedBlockIds:[],currentBlockId:ids.textBlock,operationId:'after-complete'})
    assert.equal(saved.status,'completed')
    assert.deepEqual(saved.confirmedCompletedBlockIds,[ids.textBlock])
    assert.equal((await read(db,'lesson_progress',ids.lesson,null,ids.userB)),null)
  })
  await t.test('story traversal, submitted feedback and required checks protect episode20',async()=>{
    const context={lessonId:ids.vnLesson,blockId:ids.vnBlock,storyVersionId:ids.version}
    await fail(cmd('save_episode_checkpoint',{...context,currentSceneId:ids.end,visitedSceneIds:[ids.start,ids.end],operationId:'skip-start'}))
    await cmd('save_episode_checkpoint',{...context,currentSceneId:ids.start,visitedSceneIds:[ids.start],operationId:'vn-start'})
    await fail(cmd('save_episode_checkpoint',{...context,currentSceneId:ids.end,visitedSceneIds:[ids.start,ids.end],operationId:'skip-check'}))
    await cmd('save_episode_checkpoint',{...context,currentSceneId:ids.check,visitedSceneIds:[ids.start,ids.check],operationId:'vn-check'})
    await fail(cmd('record_choice',{...context,sceneId:ids.check,choiceId:ids.correct,replay:true,operationId:'premature-feedback'}))
    const wrong=await cmd('record_choice',{...context,sceneId:ids.check,choiceId:ids.wrong,operationId:'vn-wrong'})
    assert.equal(wrong.choiceFeedback.outcome,'incorrect')
    assert.equal(wrong.currentSceneId,ids.check)
    await fail(block(ids.vnLesson,ids.vnBlock,'vn-before-end'))
    const correct=await cmd('record_choice',{...context,sceneId:ids.check,choiceId:ids.correct,operationId:'vn-correct'})
    assert.equal(correct.currentSceneId,ids.end)
    const completed=await block(ids.vnLesson,ids.vnBlock,'vn-block')
    assert.equal(completed.xpGranted,20)
    assert.equal((await cmd('complete_lesson',{lessonId:ids.vnLesson,operationId:'vn-lesson'})).xpGranted,0)
    const review=await cmd('record_choice',{...context,sceneId:ids.check,choiceId:ids.wrong,replay:true,operationId:'vn-feedback-review'})
    assert.equal(review.status,'completed')
    assert.equal(review.currentSceneId,ids.end)
    assert.equal((await block(ids.vnLesson,ids.vnBlock,'vn-replay')).xpGranted,0)
    assert.equal((await read(db,'resume',ids.vnLesson)).sceneId,ids.end)
  })
  await t.test('video union, server-time budget and90percent policy resist seeking/duplicates',async()=>{
    const context={lessonId:ids.videoLesson,blockId:ids.videoBlock}
    await fail(cmd('save_video_position',{...context,positionSeconds:100,watchedRanges:[{start:0,end:100}],operationId:'fabricated'}))
    await cmd('save_video_position',{...context,positionSeconds:0,watchedRanges:[],operationId:'video-play'})
    // Trusted test clock fixture substitutes elapsed playback instead of blocking the test for90seconds.
    await db.query("update public.user_video_progress set telemetry_started_at=now()-interval '100 seconds' where user_id=$1 and block_id=$2",[ids.userA,ids.videoBlock])
    const seek=await cmd('save_video_position',{...context,positionSeconds:100,watchedRanges:[{start:99,end:100}],operationId:'seek'})
    assert.equal(seek.completed,false)
    await fail(block(ids.videoLesson,ids.videoBlock,'seek-complete'))
    await cmd('save_video_position',{...context,positionSeconds:60,watchedRanges:[{start:0,end:60}],operationId:'video-first'})
    const combined=await cmd('save_video_position',{...context,positionSeconds:90,watchedRanges:[{start:30,end:90}],operationId:'video-second'})
    assert.deepEqual(combined.watchedRanges,[{start:0,end:90},{start:99,end:100}])
    await block(ids.videoLesson,ids.videoBlock,'video-block')
    assert.equal((await cmd('complete_lesson',{lessonId:ids.videoLesson,operationId:'video-lesson'})).xpGranted,10)
    assert.equal((await read(db,'video_progress',ids.videoLesson,ids.videoBlock)).completed,true)
    await fail(cmd('save_video_position',{...context,positionSeconds:90,watchedRanges:[],expectedRevision:0,operationId:'old-video'}),'PT409')
  })
  await t.test('fallback requires approved transcript and completed authored recap',async()=>{
    await fail(block(ids.mixedLesson,ids.mixedVideoBlock,'no-recap','accessible_fallback'))
    await block(ids.mixedLesson,ids.recapBlock,'recap')
    const fallback=await block(ids.mixedLesson,ids.mixedVideoBlock,'fallback','accessible_fallback')
    assert.equal(fallback.method,'accessible_fallback')
    assert.equal((await cmd('complete_lesson',{lessonId:ids.mixedLesson,operationId:'mixed'})).xpGranted,10)
  })
  await t.test('trusted quiz grading, feedback, mastery and retries grant25 only once',async()=>{
    const attempt={questionSetId:ids.quiz,answers:quizAnswers(false),operationId:'quiz-wrong'}
    const wrong=await cmd('submit_scored',attempt)
    assert.equal(wrong.passed,false)
    assert.equal(wrong.score,0)
    await fail(block(ids.quizLesson,ids.quizBlock,'quiz-before-pass'))
    const good=await cmd('submit_scored',{...attempt,answers:quizAnswers(),operationId:'quiz-good'})
    assert.equal(good.score,3)
    assert.equal(good.feedback.length,3)
    assert.equal(good.passed,true)
    assert.deepEqual(await cmd('submit_scored',{...attempt,answers:quizAnswers(),operationId:'quiz-good'}),good)
    await cmd('submit_scored',{...attempt,answers:quizAnswers(),operationId:'quiz-retry'})
    await block(ids.quizLesson,ids.quizBlock,'quiz-block')
    assert.equal((await cmd('complete_lesson',{lessonId:ids.quizLesson,operationId:'quiz-lesson'})).xpGranted,0)
    assert.equal((await read(db,'account')).totalXp,75)
    const mastery=(await db.query('select * from public.user_quiz_mastery where user_id=$1 and question_set_id=$2',[ids.userA,ids.quiz])).rows[0]
    assert.equal(mastery.best_score,3)
    assert.equal(mastery.attempts,3)
    assert.equal((await db.query('select count(*) count from public.streak_days where user_id=$1',[ids.userA])).rows[0].count,1)
    await fail(cmd('submit_scored',{questionSetId:ids.quiz,answers:[quizAnswers()[0],quizAnswers()[0],quizAnswers()[2]],operationId:'duplicate-answer'}))
    await fail(cmd('submit_scored',{questionSetId:ids.quiz,answers:quizAnswers().slice(0,2),operationId:'missing-answer'}))
  })
})
