import test from 'node:test'
import assert from 'node:assert/strict'
import { createTestDatabase, asRole, read, command, ids, uuid } from './harness.mjs'

test('SQL grants, RLS, publication and Storage protect anon/A/B boundaries', async t => {
  const db = await createTestDatabase()
  t.after(() => db.close())
  const fails = (work, code) => assert.rejects(work, error => error.code === code)
  await t.test('published relational DTOs have stable UUID identities and no keys', async () => {
    const catalog = await read(db, 'chapters', null, null, null)
    assert.equal(catalog.length, 1)
    assert.equal(catalog[0].lessonRefs.length, 5)
    assert.equal((await read(db, 'lesson', ids.lesson, null, null)).blocks[0].documentId, ids.document)
    assert.equal((await read(db, 'document', ids.document, null, null)).sections[0].kind, 'paragraph')
    const story = await read(db, 'story', ids.version, null, null)
    assert.equal(story.scenes.length, 3)
    assert.equal(story.scenes[1].choices[0].isCorrect, undefined)
    assert.equal(story.scenes[1].choices[0].explanation, undefined)
    const quiz = await read(db, 'quiz', ids.quiz, null, null)
    assert.equal(quiz.questions.length, 3)
    assert.equal(quiz.questions[0].explanation, undefined)
    assert.equal(quiz.questions[0].options[0].isCorrect, undefined)
    const media = await read(db, 'media', ids.video, null, null)
    assert.equal(media.poster.storageRef, 'published-media/fixture-poster.webp')
    assert.equal(media.captionTracks[0].storageRef, 'published-media/fixture.vtt')
    assert.equal(media.transcript.id, ids.transcript)
    for (const [kind,id] of [['chapter',ids.draftChapter],['lesson',ids.draftLesson],['document',ids.draftDocument],['media',ids.draftMedia]]) await fails(read(db,kind,id,null,null),'P0002')
  })
  await t.test('anon cannot read private keys, user data or invoke writes', async () => {
    for (const table of ['profiles','user_settings','user_lesson_progress','reward_ledger']) {
      const rows = await asRole(db,'anon',null,tx => tx.query(`select * from public.${table}`))
      assert.equal(rows.rows.length,0)
    }
    await fails(asRole(db,'anon',null,tx => tx.query('select * from private.question_answer_keys')),'42501')
    await fails(asRole(db,'anon',null,tx => tx.query('select * from private.scene_answer_keys')),'42501')
    await fails(command(db,'complete_lesson',{lessonId:ids.lesson,operationId:'anon'},null),'42501')
    await fails(read(db,'account',null,null,null),'42501')
  })
  await t.test('A cannot read/write B; identity body override and direct XP writes fail', async () => {
    await command(db,'complete_block',{lessonId:ids.lesson,blockId:ids.textBlock,operationId:'a-text'})
    await command(db,'complete_lesson',{lessonId:ids.lesson,operationId:'a-lesson'})
    assert.equal((await read(db,'account')).totalXp,10)
    assert.equal((await read(db,'account',null,null,ids.userB)).totalXp,0)
    const rows = await asRole(db,'authenticated',ids.userB,tx => tx.query('select * from public.user_lesson_progress where user_id=$1',[ids.userA]))
    assert.equal(rows.rows.length,0)
    const profile = await read(db,'profile')
    assert.deepEqual(profile,{ id:ids.userA,displayName:'Fixture A',locale:'vi-VN' })
    await fails(command(db,'complete_block',{lessonId:ids.lesson,blockId:ids.textBlock,userId:ids.userB,operationId:'override'}),'22023')
    await fails(asRole(db,'authenticated',ids.userA,tx => tx.query("update public.profiles set display_name='spoof' where id=$1",[ids.userB])),'42501')
    await fails(asRole(db,'authenticated',ids.userA,tx => tx.query("insert into public.reward_ledger(user_id,reward_type,activity_id,eligibility_version,xp_delta,idempotency_key) values($1,'lesson',$2,'1',999,'spoof')",[ids.userA,ids.lesson])),'42501')
    await fails(asRole(db,'authenticated',ids.userA,tx => tx.query("update public.lessons set status='published' where id=$1",[ids.draftLesson])),'42501')
  })
  await t.test('private helpers have no direct client execution grants', async () => {
    const rows = await db.query("select proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and has_function_privilege('authenticated',p.oid,'EXECUTE')")
    assert.deepEqual(rows.rows,[])
    await fails(asRole(db,'authenticated',ids.userA,tx => tx.query('select private.grant_reward($1,$2,$3,$4,99)',[ids.userA,'lesson',ids.lesson,'1'])),'42501')
    const roleFields = await db.query("select column_name from information_schema.columns where table_schema='public' and table_name='profiles' and column_name in ('role','is_admin')")
    assert.equal(roleFields.rows.length,0)
  })
  await t.test('published roots, children, choice keys and append-only ledger reject mutation', async () => {
    await fails(db.query('update public.lessons set title=$1 where id=$2',['changed',ids.lesson]),'22023')
    await fails(db.query('update public.lesson_blocks set required=false where id=$1',[ids.textBlock]),'22023')
    await fails(db.query('delete from public.scenes where id=$1',[ids.start]),'22023')
    await fails(db.query('update public.scene_choices set label=$1 where id=$2',['changed',ids.correct]),'22023')
    await fails(db.query('update private.question_answer_keys set explanation=$1 where question_id=$2',['changed',ids.question1]),'22023')
    await fails(db.query('update private.scene_answer_keys set is_correct=false where choice_id=$1',[ids.correct]),'22023')
    await fails(db.query('update public.reward_ledger set xp_delta=99 where user_id=$1',[ids.userA]),'42501')
  })
  await t.test('publication fails closed for draft references and unsafe fallback resources', async () => {
    await fails(db.query("update public.lessons set status='published' where id=$1",[ids.draftLesson]),'22023')
    const mediaId=uuid(900)
    await db.query("insert into public.media_assets(id,kind,title,storage_ref,duration_seconds) values($1,'video','DRAFT','published-media/new.mp4',10)",[mediaId])
    await db.query("insert into public.transcripts(media_asset_id,label,storage_ref,document_id) values($1,'DRAFT','draft-media/private.txt',$2)",[mediaId,ids.draftDocument])
    await fails(db.query("update public.media_assets set review_status='published' where id=$1",[mediaId]),'22023')
  })
  await t.test('Storage anon reads only approved paths; avatars stay account scoped', async () => {
    const anon = await asRole(db,'anon',null,tx => tx.query('select bucket_id,name from storage.objects order by name'))
    assert.deepEqual(anon.rows.map(row=>row.name),['fixture-video.mp4','fixture.txt','fixture.vtt'])
    const own = await asRole(db,'authenticated',ids.userA,tx => tx.query("select name from storage.objects where bucket_id='user-avatars'"))
    assert.deepEqual(own.rows.map(row=>row.name),[`${ids.userA}/avatar.webp`])
    await fails(asRole(db,'authenticated',ids.userA,tx => tx.query("insert into storage.objects(bucket_id,name) values('user-avatars',$1)",[`${ids.userB}/spoof.webp`])),'42501')
    await fails(asRole(db,'authenticated',ids.userA,tx => tx.query("insert into storage.objects(bucket_id,name) values('published-media','spoof.webp')")),'42501')
    const buckets=await db.query('select public from storage.buckets')
    assert.ok(buckets.rows.every(row=>row.public===false))
  })
})
