import assert from 'node:assert/strict'
import test from 'node:test'
import { findBrowser, withChromePage } from './chromeHarness.mjs'
import { pwaHarness } from './pwaHarness.mjs'
const condition = offline => ({offline,latency:0,downloadThroughput:-1,uploadThroughput:-1})
const storage = cdp => cdp.evaluate('({pending:localStorage.getItem("suchill.pending.v1"),auth:localStorage.getItem("owned-auth-session")})')
const cacheKeys = cdp => cdp.evaluate('(async()=>{const keys=[];for(const name of await caches.keys()){if(name.startsWith("suchill-static-"))for(const entry of await (await caches.open(name)).keys())keys.push({cache:name,url:entry.url})}return keys})()')
const version = cdp => cdp.evaluate('window.__pwaQA.version')

test('real Chrome: install/control, two-build safe update, queue serialization, multitab and failed install', async () => {
  await pwaHarness(async fixture => {
    const {origin,versions,seen}=fixture
    assert.notEqual(versions[0].meta.version,versions[1].meta.version)
    assert.equal(versions[0].meta.precache.some(path=>path.includes('pwa-deferred')),false)
    await withChromePage(findBrowser(),origin+'/',async cdp => {
      await cdp.waitFor('Boolean(window.__pwaQA && navigator.serviceWorker.controller)', 'Installed worker controls fixture')
      assert.equal(await version(cdp),'v1')
      const original=await storage(cdp)
      assert.ok(original.pending.includes('owned-fixed-operation')); assert.ok(original.auth.includes('synthetic-owned-session'))
      await cdp('Page.reload')
      await cdp.waitFor('Boolean(window.__pwaQA)')
      assert.equal(await version(cdp),'v1'); assert.deepEqual(await storage(cdp),original)
      const manifest=await cdp('Page.getAppManifest')
      assert.equal(manifest.errors.length,0)
      const metadata=JSON.parse(manifest.data)
      assert.equal(metadata.display,'standalone'); assert.equal(metadata.start_url,'/'); assert.equal(metadata.lang,'vi')
      const installability=await cdp('Page.getInstallabilityErrors')
      assert.deepEqual(installability.installabilityErrors,[],'Chrome desktop manifest meets installability checks')
      await cdp.evaluate('document.cookie="ownedSyntheticCookie=must-not-be-sent-to-cache-fetches"')
      assert.equal(await cdp.evaluate('window.__pwaQA.loadDeferred()'),'Deferred static fixture v1')
      const oldKeys=await cacheKeys(cdp)
      const oldDeferred=oldKeys.find(entry=>/pwa-deferred/.test(entry.url))
      assert.ok(oldDeferred, 'Deferred chunk cached only after visiting it')
      await cdp.evaluate('(async()=>{for(const path of ["/auth/private","/api/private","/rest/private","/functions/private","/storage/private","/assets/owned-unlisted.js","/manifest.webmanifest?owned=private"]){await fetch(path)}await fetch("/manifest.webmanifest",{headers:{Authorization:"owned-synthetic"}});await fetch("/api/private",{method:"POST",body:"owned-only"});await fetch("https://example.invalid/owned",{mode:"no-cors"}).catch(()=>{})})()')
      const privateKeys=await cacheKeys(cdp)
      assert.equal(privateKeys.some(entry=>/private|owned-unlisted|\?/.test(entry.url)),false)
      const anonymous=seen.filter(item=>/pwa-deferred/.test(item.path) || item.path==='/assets/owned-unlisted.js')
      assert.ok(anonymous.length>0); assert.equal(anonymous.some(item=>item.cookie||item.authorization),false)
      fixture.setOffline(true); await cdp('Network.emulateNetworkConditions',condition(true))
      await cdp('Page.navigate',{url:origin+'/owned-deep-link'})
      await cdp.waitFor('Boolean(window.__pwaQA)')
      assert.equal(await version(cdp),'v1'); assert.deepEqual(await storage(cdp),original)
      await cdp('Page.navigate',{url:origin+'/?recovery=1&code=owned-synthetic-code'})
      await cdp.waitFor('document.body.innerText.includes("Chưa có kết nối")')
      assert.equal(await cdp.evaluate('location.search'),'?recovery=1&code=owned-synthetic-code')
      assert.equal(await cdp.evaluate('Boolean(window.__pwaQA)'),false)
      assert.deepEqual(await storage(cdp),original)
      assert.equal((await cacheKeys(cdp)).some(entry=>entry.url.includes('owned-synthetic-code')),false)
      await cdp('Page.navigate',{url:origin+'/#type=recovery&access_token=owned-fragment-token'})
      await cdp.waitFor('Boolean(window.__pwaQA) || document.body.innerText.includes("Chưa có kết nối")')
      // Offline callback navigation renders anonymous shell/fallback and preserves the URL; no credential cache entries.
      assert.equal(await cdp.evaluate('location.hash'),'#type=recovery&access_token=owned-fragment-token')
      assert.equal((await cacheKeys(cdp)).some(entry=>entry.url.includes('owned-fragment-token')),false)
      assert.deepEqual(await storage(cdp),original)
      fixture.setOffline(false); await cdp('Network.emulateNetworkConditions',condition(false))
      await cdp('Page.navigate',{url:origin+'/'})
      await cdp.waitFor('Boolean(window.__pwaQA)')
      const oldTab=await cdp.newPage(origin+'/')
      await oldTab.waitFor('Boolean(window.__pwaQA)')
      const oldLoader=(await oldTab('Page.getFrameTree')).frameTree.frame.loaderId
      fixture.publish(1)
      await cdp.evaluate('window.__pwaQA.update()')
      await cdp.waitFor('window.__pwaQA.snapshot().status==="waiting"', 'v2 stays waiting')
      assert.equal(await cdp.evaluate('window.__pwaQA.snapshot().waitingVersion'),versions[1].meta.version)
      assert.equal(await version(cdp),'v1'); assert.deepEqual(await storage(cdp),original)
      await cdp.evaluate('window.__pwaQA.activate()')
      await cdp.waitFor('window.__pwaQA.result()===false')
      assert.equal(await cdp.evaluate('(async()=>Boolean((await navigator.serviceWorker.getRegistration()).waiting))()'),true)
      await cdp.evaluate('window.__pwaQA.holdQueue()')
      await cdp.waitFor('window.__pwaQA.held()')
      await cdp.evaluate('window.__pwaQA.setSafe(true);window.__pwaQA.activate()')
      await cdp.waitFor('window.__pwaQA.snapshot().status==="updating"')
      assert.equal(await cdp.evaluate('window.__pwaQA.result()'),'pending')
      assert.equal(await version(cdp),'v1')
      await cdp.evaluate('window.__pwaQA.setSafe(false);window.__pwaQA.releaseQueue()')
      await cdp.waitFor('window.__pwaQA.result()===false')
      assert.equal(await cdp.evaluate('window.__pwaQA.snapshot().status'),'waiting')
      await cdp.evaluate('window.__pwaQA.setSafe(true);window.__pwaQA.activate()')
      await cdp.waitFor('window.__pwaQA?.version==="v2"','Explicit safe update reloads v2')
      assert.deepEqual(await storage(cdp),original)
      assert.equal(await version(oldTab),'v1','Another existing tab is never automatically reloaded')
      assert.equal((await oldTab('Page.getFrameTree')).frameTree.frame.loaderId,oldLoader)
      await oldTab('Network.emulateNetworkConditions',condition(true))
      const prior=await oldTab.evaluate('fetch('+JSON.stringify(oldDeferred.url)+').then(response=>({ok:response.ok,text:response.text()})).then(async value=>({ok:value.ok,text:await value.text}))')
      assert.equal(prior.ok,true); assert.ok(prior.text.includes('v1'))
      const finalKeys=await cacheKeys(cdp)
      assert.ok(finalKeys.some(entry=>entry.cache.endsWith(versions[0].meta.version)))
      assert.ok(finalKeys.some(entry=>entry.cache.endsWith(versions[1].meta.version)))
      await oldTab.close()
      fixture.failInstall()
      await cdp.evaluate('window.__pwaQA.update().catch(()=>{})')
      await cdp.waitFor('(async()=>{const r=await navigator.serviceWorker.getRegistration();return !r.installing&&!r.waiting})()', 'Failed v3 install leaves v2 active')
      fixture.setOffline(true); await cdp('Network.emulateNetworkConditions',condition(true))
      await cdp('Page.reload')
      await cdp.waitFor('window.__pwaQA?.version==="v2"')
      assert.deepEqual(await storage(cdp),original)
      assert.equal((await cacheKeys(cdp)).some(entry=>entry.cache.endsWith('ffffffffffffffffffff')),false)
      assert.equal((await cacheKeys(cdp)).some(entry=>/private|owned-unlisted|\?/.test(entry.url)),false)
    }, {mountedSelector:'main'})
  })
})
