import { randomBytes, randomUUID } from 'node:crypto'
import { createClient } from '@supabase/supabase-js'
import { loadHostedConfig } from '../hosted-tests/config.mjs'

// These clients talk to hosted Auth/PostgREST. No Auth or HTTP response is faked.
export async function createAuthHarness() {
  const config = await loadHostedConfig()
  const clients = [], users = new Map(), disposed = new WeakSet()
  const timedFetch = (input, init = {}) => fetch(input, {
    ...init, signal: init.signal
      ? AbortSignal.any([init.signal, AbortSignal.timeout(30_000)]) : AbortSignal.timeout(30_000),
  })
  function client(storage = memoryStorage(), key = config.publishableKey) {
    const result = createClient(config.url, key, {
      auth: { storage, storageKey: `suchill-auth-${randomUUID()}`, persistSession: true,
        autoRefreshToken: false, detectSessionInUrl: false },
      global: { fetch: timedFetch },
    })
    clients.push(result)
    return result
  }
  function restoredClient(storage, storageKey) {
    const result = createClient(config.url, config.publishableKey, {
      auth: { storage, storageKey, persistSession: true, autoRefreshToken: false, detectSessionInUrl: false },
      global: { fetch: timedFetch },
    })
    clients.push(result)
    return result
  }
  const admin = client(memoryStorage(), config.secretKey)
  async function dispose(sdk) {
    await sdk.auth.dispose()
    disposed.add(sdk)
  }
  async function provision(name, confirmed = true) {
    const email = `suchill-auth-${randomUUID()}@example.com`
    const password = `S!c9-${randomBytes(24).toString('base64url')}`
    const metadata = { displayName: `Hosted Auth ${name}`, timezone: 'Asia/Ho_Chi_Minh' }
    const response = confirmed
      ? await admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: metadata })
      : await admin.auth.admin.generateLink({ type: 'signup', email, password,
        options: { data: metadata, redirectTo: 'http://localhost:5173' } })
    // Never include a response/error/token/credential in a thrown diagnostic.
    if (response.error || !response.data.user?.id) {
      const status = typeof response.error?.status === 'number' ? response.error.status : 'unknown'
      const code = /^[a-z_]{1,60}$/.test(response.error?.code ?? '') ? response.error.code : 'unavailable'
      throw new Error(`Test Auth user provisioning failed (status ${status}, code ${code})`)
    }
    const fixture = { email, password, id: response.data.user.id, displayName: metadata.displayName,
      properties: 'properties' in response.data ? response.data.properties : null }
    users.set(fixture.id, fixture)
    return fixture
  }
  async function cleanup() {
    let failed = false
    for (const sdk of clients) {
      if (sdk !== admin && !disposed.has(sdk)) {
        try { const response = await sdk.auth.signOut(); failed ||= !!response.error } catch { failed = true }
        await dispose(sdk)
      }
    }
    // Only IDs generated by this run are eligible for deletion.
    for (const id of users.keys()) {
      try { const response = await admin.auth.admin.deleteUser(id); failed ||= !!response.error } catch { failed = true }
    }
    users.clear()
    await dispose(admin)
    if (failed) throw new Error('Auth test cleanup requires inspection; no unrelated users were touched')
  }
  return { config, admin, client, restoredClient, provision, dispose, cleanup }
}

export function memoryStorage() {
  const values = new Map()
  return { getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value),
    removeItem: key => values.delete(key), keys: () => [...values.keys()] }
}

export function requireSuccess(result, label) {
  if (!result.ok) throw new Error(`${label}: domain operation failed (${result.error})`)
  return result.value
}
